from app.services.google_drive_service import (
    get_drive_service,
    get_or_create_output_folder,
    upload_file_to_drive,
)


def main():

    print("===== GOOGLE DRIVE UPLOAD TEST =====\n")

    # 1. Connect to Drive
    print("1. Connecting to Google Drive...")

    service = get_drive_service()

    print("Google Drive connected.\n")

    # 2. Get/create output folder
    print("2. Getting output folder...")

    folder_id = get_or_create_output_folder(
        service
    )

    print(
        f"Output folder ID: {folder_id}\n"
    )

    # 3. Files generated by our pipeline
    files_to_upload = [
        "data/summaries/untitled_summary.txt",
        "data/paraphrased/untitled_paraphrased.txt",
        "data/audio/untitled_full_document.mp3",
    ]

    # 4. Upload files
    print("3. Uploading generated files...\n")

    uploaded_files = []

    for file_path in files_to_upload:

        uploaded = upload_file_to_drive(
            service,
            file_path,
            folder_id
        )

        uploaded_files.append(uploaded)

    # 5. Display results
    print("\n===== UPLOADED FILES =====\n")

    for file in uploaded_files:

        print(f"Name: {file['name']}")
        print(f"ID: {file['id']}")
        print(f"Type: {file['mimeType']}")
        print(f"Size: {file.get('size', 'N/A')}")
        print(
            f"Link: "
            f"{file.get('webViewLink', 'N/A')}"
        )
        print()

    print("===== UPLOAD TEST PASSED =====")


if __name__ == "__main__":
    main()